google_analytics: G-B8ZTJ0M4L1

theme: jekyll-theme-minimal
title: Ultimate Cartridge
description: Ultimate Cartridge!
languages: ["en", "ja"]
default_lang: "ja"
url: "https://ultimate-cartridge.jp"
baseurl: ""
keywords: mc cartridge,mc cartridge repair,cartridge needle repair,cartridge stylus repair,ortofon,koetsu,my sonic lab,Bluelectric,jan allaerts,lyra,Etsuro,emt,Clearaudio,Kiseki,linn,vdh,Ven Den HUL,Dynavector,IKEDA,ds audio,Audio-Technica;MCカートリッジの修理,オルトフォン,コーツ,マイソニックラボ,ブルエレクトリック,ヤンアラーツ,ライラ,エツロー,EMT,クリアオーディオ,キセキ,リン,VDH,ダイナベクター,イケダ,DSオーディオ,オーディオテクニカ

collections_dir: collections
collections:
  oem:
    output: true
    permalink: /:lang/oem/:name/
  news:
    output: true
    permalink: /:lang/news/:name/

plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-seo-tag
  - jekyll-sitemap