theme: jekyll-theme-minimal
title: Ultimate Cartridge
description: Bookmark this to keep an eye on my project updates!
languages: ["en", "ja"]
default_lang: "ja"

collections_dir: collections
collections:
  oem:
    output: true
    permalink: /:lang/oem/:name/
  top:
    output: true
    permalink: /:lang/top/:name/