theme: jekyll-theme-minimal
title: Ultimate Cartridge
description: Ultimate Cartridge!
languages: ["en", "ja"]
default_lang: "ja"

collections_dir: collections
collections:
  oem:
    output: true
    permalink: /:lang/oem/:name/
  news:
    output: true
    permalink: /:lang/news/:name/